# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: campnight_user_engine_development
  username: k43g0n
  host: localhost
  pool: 5
  port: 5432
  
